In [ ]:
# importing libararies

In [26]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectPercentile , chi2
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , f1_score

In [27]:
dataset = pd.read_csv("C:\\Users\\engma\\Desktop\\diabetes_binary_health_indicators_BRFSS2015.csv")

In [28]:
dataset.isnull().sum()

Diabetes_binary         0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [29]:
sc = StandardScaler()

In [30]:
y = dataset.iloc[:,:1]
print (y[:10])
y.shape

   Diabetes_binary
0              0.0
1              0.0
2              0.0
3              0.0
4              0.0
5              0.0
6              0.0
7              0.0
8              1.0
9              0.0


(253680, 1)

In [31]:
x = dataset.iloc[:,1:]
print (x[:10])

   HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  HeartDiseaseorAttack  \
0     1.0       1.0        1.0  40.0     1.0     0.0                   0.0   
1     0.0       0.0        0.0  25.0     1.0     0.0                   0.0   
2     1.0       1.0        1.0  28.0     0.0     0.0                   0.0   
3     1.0       0.0        1.0  27.0     0.0     0.0                   0.0   
4     1.0       1.0        1.0  24.0     0.0     0.0                   0.0   
5     1.0       1.0        1.0  25.0     1.0     0.0                   0.0   
6     1.0       0.0        1.0  30.0     1.0     0.0                   0.0   
7     1.0       1.0        1.0  25.0     1.0     0.0                   0.0   
8     1.0       1.0        1.0  30.0     1.0     0.0                   1.0   
9     0.0       0.0        1.0  24.0     0.0     0.0                   0.0   

   PhysActivity  Fruits  Veggies  ...  AnyHealthcare  NoDocbcCost  GenHlth  \
0           0.0     0.0      1.0  ...            1.0          0

In [32]:
FeatureSelection = SelectPercentile(score_func=chi2,percentile=90)
x = FeatureSelection.fit_transform(x,y)

In [33]:
print (x[:10])


[[ 1.  1. 40.  1.  0.  0.  0.  0.  1.  0.  0.  5. 18. 15.  1.  9.  4.  3.]
 [ 0.  0. 25.  1.  0.  0.  1.  0.  0.  0.  1.  3.  0.  0.  0.  7.  6.  1.]
 [ 1.  1. 28.  0.  0.  0.  0.  1.  0.  0.  1.  5. 30. 30.  1.  9.  4.  8.]
 [ 1.  0. 27.  0.  0.  0.  1.  1.  1.  0.  0.  2.  0.  0.  0. 11.  3.  6.]
 [ 1.  1. 24.  0.  0.  0.  1.  1.  1.  0.  0.  2.  3.  0.  0. 11.  5.  4.]
 [ 1.  1. 25.  1.  0.  0.  1.  1.  1.  0.  0.  2.  0.  2.  0. 10.  6.  8.]
 [ 1.  0. 30.  1.  0.  0.  0.  0.  0.  0.  0.  3.  0. 14.  0.  9.  6.  7.]
 [ 1.  1. 25.  1.  0.  0.  1.  0.  1.  0.  0.  3.  0.  0.  1. 11.  4.  4.]
 [ 1.  1. 30.  1.  0.  1.  0.  1.  1.  0.  0.  5. 30. 30.  1.  9.  5.  1.]
 [ 0.  0. 24.  0.  0.  0.  0.  0.  1.  0.  0.  2.  0.  0.  0.  8.  4.  3.]]


In [34]:
x.shape

(253680, 18)

In [35]:
x = sc.fit_transform(x)

# training test spliting 

In [36]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.33,random_state=44)
print (x_train.shape)
print (x_test.shape)
print (y_train.shape)
print (y_test.shape)

(169965, 18)
(83715, 18)
(169965, 1)
(83715, 1)


In [37]:
y_train=np.ravel(y_train)
print(y_train.shape)

(169965,)


In [38]:
svm_model=svm.SVC(kernel='linear')
svm_model.fit(x_train,y_train)

SVC(kernel='linear')

In [39]:
train_score = svm_model.score(x_train,y_train) 
test_score = svm_model.score(x_test,y_test)
print(train_score , test_score)

0.8602006295413762 0.861613808755898


In [40]:
y_predict = svm_model.predict(x_test) 
AccuracyScore = accuracy_score(y_predict,y_test)
print(AccuracyScore)

0.861613808755898


In [41]:
 from sklearn import metrics
print("f1_score of svm",metrics.f1_score(y_test, y_predict)*100)

f1_score of svm 0.0
